//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Pft.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace ManagedClient.Pft {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPftListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public partial class PftBaseListener : IPftListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.WarningOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWarningOuter([NotNull] PftParser.WarningOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.WarningOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWarningOuter([NotNull] PftParser.WarningOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionParen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionParen([NotNull] PftParser.ConditionParenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionParen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionParen([NotNull] PftParser.ConditionParenContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FormatItemPlus"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormatItemPlus([NotNull] PftParser.FormatItemPlusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FormatItemPlus"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormatItemPlus([NotNull] PftParser.FormatItemPlusContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FormatExitOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormatExitOuter([NotNull] PftParser.FormatExitOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FormatExitOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormatExitOuter([NotNull] PftParser.FormatExitOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.CommandX"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandX([NotNull] PftParser.CommandXContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.CommandX"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandX([NotNull] PftParser.CommandXContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.TraceOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTraceOuter([NotNull] PftParser.TraceOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.TraceOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTraceOuter([NotNull] PftParser.TraceOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.DebugOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDebugOuter([NotNull] PftParser.DebugOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.DebugOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDebugOuter([NotNull] PftParser.DebugOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.rightHand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRightHand([NotNull] PftParser.RightHandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.rightHand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRightHand([NotNull] PftParser.RightHandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.leftHand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeftHand([NotNull] PftParser.LeftHandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.leftHand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeftHand([NotNull] PftParser.LeftHandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fatal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFatal([NotNull] PftParser.FatalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fatal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFatal([NotNull] PftParser.FatalContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ErrorOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterErrorOuter([NotNull] PftParser.ErrorOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ErrorOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitErrorOuter([NotNull] PftParser.ErrorOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.SlashNewLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSlashNewLine([NotNull] PftParser.SlashNewLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.SlashNewLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSlashNewLine([NotNull] PftParser.SlashNewLineContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fieldPresense"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldPresense([NotNull] PftParser.FieldPresenseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fieldPresense"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldPresense([NotNull] PftParser.FieldPresenseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] PftParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] PftParser.StatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.TrimFunctionOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrimFunctionOuter([NotNull] PftParser.TrimFunctionOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.TrimFunctionOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrimFunctionOuter([NotNull] PftParser.TrimFunctionOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.conditionalStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalStatement([NotNull] PftParser.ConditionalStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.conditionalStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalStatement([NotNull] PftParser.ConditionalStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] PftParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] PftParser.ProgramContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.sFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSFunction([NotNull] PftParser.SFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.sFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSFunction([NotNull] PftParser.SFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ModeSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModeSwitch([NotNull] PftParser.ModeSwitchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ModeSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModeSwitch([NotNull] PftParser.ModeSwitchContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.fieldReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldReference([NotNull] PftParser.FieldReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.fieldReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldReference([NotNull] PftParser.FieldReferenceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionNot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionNot([NotNull] PftParser.ConditionNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionNot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionNot([NotNull] PftParser.ConditionNotContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.NoccOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoccOuter([NotNull] PftParser.NoccOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.NoccOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoccOuter([NotNull] PftParser.NoccOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.PercentNewLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPercentNewLine([NotNull] PftParser.PercentNewLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.PercentNewLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPercentNewLine([NotNull] PftParser.PercentNewLineContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FieldReferenceOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldReferenceOuter([NotNull] PftParser.FieldReferenceOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FieldReferenceOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldReferenceOuter([NotNull] PftParser.FieldReferenceOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.FatalOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFatalOuter([NotNull] PftParser.FatalOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.FatalOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFatalOuter([NotNull] PftParser.FatalOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionField([NotNull] PftParser.ConditionFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionField([NotNull] PftParser.ConditionFieldContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.debug"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDebug([NotNull] PftParser.DebugContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.debug"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDebug([NotNull] PftParser.DebugContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.SFunctionOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSFunctionOuter([NotNull] PftParser.SFunctionOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.SFunctionOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSFunctionOuter([NotNull] PftParser.SFunctionOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionString([NotNull] PftParser.ConditionStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionString([NotNull] PftParser.ConditionStringContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.UnconditionalLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnconditionalLiteral([NotNull] PftParser.UnconditionalLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.UnconditionalLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnconditionalLiteral([NotNull] PftParser.UnconditionalLiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.MfnWithLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMfnWithLength([NotNull] PftParser.MfnWithLengthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.MfnWithLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMfnWithLength([NotNull] PftParser.MfnWithLengthContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.IoccOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIoccOuter([NotNull] PftParser.IoccOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.IoccOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIoccOuter([NotNull] PftParser.IoccOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.StringTestDirect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringTestDirect([NotNull] PftParser.StringTestDirectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.StringTestDirect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringTestDirect([NotNull] PftParser.StringTestDirectContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.formatExit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormatExit([NotNull] PftParser.FormatExitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.formatExit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormatExit([NotNull] PftParser.FormatExitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.error"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterError([NotNull] PftParser.ErrorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.error"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitError([NotNull] PftParser.ErrorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.trimFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrimFunction([NotNull] PftParser.TrimFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.trimFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrimFunction([NotNull] PftParser.TrimFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.trace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrace([NotNull] PftParser.TraceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.trace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrace([NotNull] PftParser.TraceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.SimpleMfn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleMfn([NotNull] PftParser.SimpleMfnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.SimpleMfn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleMfn([NotNull] PftParser.SimpleMfnContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.Break"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreak([NotNull] PftParser.BreakContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.Break"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreak([NotNull] PftParser.BreakContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionalStatementOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalStatementOuter([NotNull] PftParser.ConditionalStatementOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionalStatementOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalStatementOuter([NotNull] PftParser.ConditionalStatementOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.nocc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNocc([NotNull] PftParser.NoccContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.nocc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNocc([NotNull] PftParser.NoccContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.HashNewLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHashNewLine([NotNull] PftParser.HashNewLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.HashNewLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHashNewLine([NotNull] PftParser.HashNewLineContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.GlobalReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalReference([NotNull] PftParser.GlobalReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.GlobalReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalReference([NotNull] PftParser.GlobalReferenceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.ConditionAndOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionAndOr([NotNull] PftParser.ConditionAndOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.ConditionAndOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionAndOr([NotNull] PftParser.ConditionAndOrContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.CommandC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandC([NotNull] PftParser.CommandCContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.CommandC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandC([NotNull] PftParser.CommandCContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.groupStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupStatement([NotNull] PftParser.GroupStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.groupStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupStatement([NotNull] PftParser.GroupStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.StringTestReverse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringTestReverse([NotNull] PftParser.StringTestReverseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.StringTestReverse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringTestReverse([NotNull] PftParser.StringTestReverseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.iocc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIocc([NotNull] PftParser.IoccContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.iocc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIocc([NotNull] PftParser.IoccContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.Comma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComma([NotNull] PftParser.CommaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.Comma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComma([NotNull] PftParser.CommaContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PftParser.warning"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWarning([NotNull] PftParser.WarningContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PftParser.warning"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWarning([NotNull] PftParser.WarningContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace ManagedClient.Pft
